import type { Metadata } from "next";
import { Geist, Geist_Mono, Pompiere } from "next/font/google";
import "./globals.css";

import ConstructionPage from "../components/maintenance/ConstructionPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pompier = Pompiere({
  subsets: ["latin"],
  weight: ["400"], // Pompier solo tiene peso 40
  variable: "--font-pompier", // Crea una variable CSS para usarla
});

export const metadata: Metadata = {
  title: "MUL",
  description: "Generated by TMGC",
};
const IS_MAINTENANCE_MODE = process.env.NEXT_PUBLIC_MAINTENANCE_MODE === "true";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (IS_MAINTENANCE_MODE) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${pompier.variable} antialiased`}
        >
          <ConstructionPage />
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
